version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    networks:
      cloud:
        ipv4_address: 172.19.0.6
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always
    networks:
      cloud:
        ipv4_address: 172.19.0.5

  app:
    image: nextcloud:fpm-alpine
    restart: always
    networks:
      cloud:
        ipv4_address: 172.19.0.4
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 8080:80
    networks:
      cloud:
        ipv4_address: 172.19.0.2
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    networks:
      cloud:
        ipv4_address: 172.19.0.3
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud: 
  
networks:
  cloud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
